# Kafka broker
kafka.bootstrap.servers=kafka:9092

# HTTP server
http.host=0.0.0.0
http.port=18082

# Management API
http.management.host=0.0.0.0
http.management.port=8081

# Consumer settings
consumer.request.timeout.ms=30000
consumer.session.timeout.ms=30000

# Producer settings
producer.acks=1
